Portfolio: Desktop version.
maximoortelli/Portfolio-setup-and-mobile-first pull request #5
Opened 2023-05-11 19:44 UTC by maximoortelli

### **Portfolio Updates:**

- _The project in mobile version is now reactive and available for PC._

- _In addition, the index.html and style.css files were updated._

- _New images were added to the portfolio._

2023-05-11 20:16 UTC, OyePriscilla requested changes
Hi @maximoortelli 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
App responsive ✔️ 
Use CSS media query ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 20:16 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly reduce the margin between each cards according to the given template. 👍 

## Your Design

<img width="901" alt="Untitled" src="https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/103386183/c957eeb0-dbc5-4cd1-a7f2-11534d03d593">

## Figma Design
<img width="506" alt="Untitled" src="https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/103386183/63e94230-1b88-4b78-8d1d-b65bd2583081">

2023-05-11 20:16 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly please do a little adjustment (`social media icons alignment`, `tech stacks' border radius` and the `hr element`) to the elements marked out in the image below. 

## Figma Design
<img width="539" alt="Untitled" src="https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/103386183/a953ccc9-6ea6-41b7-8d6c-4bd3728c008f">

## Your Design
<img width="860" alt="Untitled" src="https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/103386183/b7df06f9-05a1-40b3-83db-ab7c92ffbe23">

2023-05-12 02:44 UTC, maximoortelli commented on style.css
> +  }
Thank you very much for the review, the changes have already been made satisfactorily.

2023-05-12 03:37 UTC, Efiamotu-1 requested changes
Hi @maximoortelli  

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 03:37 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- This requirement is optional only because it was not expressly stated by the previous reviewer and it is important to add it to the design structure so that your design completetly matches the figma template.
- [ ] The Get in touch button as shown in the figma template below is centered so i kindly suggest that you also center the button on your portfolio design. :+1: 
![get-in](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/c49a17b5-289c-4589-bac9-4eb8b0ed2268)

2023-05-12 03:37 UTC, Efiamotu-1 commented on index.html
- As pointed out by the previous reviewer in this [review link](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/pull/5#discussion_r1191642108) there is alot of spacing between each work card as shown from your designs below.
- [ ] please kindly look into reducing the amount of space used to separate each card on the desktop version of your website, it is important to completely follow the figma template and design your webpage in such format as this shows recruiters you pay alot of attention to details. :+1:  :sparkles: 
- figma design
![t-f-1](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/a8fcf3c1-c2dc-49be-922d-8bd33c65a944)

- your designs
![t-s-1](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/38a59572-edcb-4e79-98ed-05e76b7e
![t-s-2](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/20115320-c21c-4291-8eee-dda486af0a4a)
a394)
![t-s-3](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/f14099bd-f962-4a94-a3b7-71bd1829ee00)

2023-05-12 03:37 UTC, Efiamotu-1 commented on index.html
- The previous reviewer requested you styled the technologies section of your desktop version to look like the figma but in doing so you messed up the design as shown in the image below, please kindly fix the design anf implement the previous reviewers [requirement](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/pull/5#discussion_r1191646872) for this section :+1: 
- [ ] You can make use of `border-radius: 8px` to style the border radius so it matches the one on figma. all see the [figma template](l7SqJ3ZfkAKih9sFxvWSR4) for accurate design specifications
- your design
![t-s-4](https://github.com/maximoortelli/Portfolio-setup-and-mobile-first/assets/89055502/87a402ef-1852-4c13-ae47-b29e498bf154)

2023-05-12 15:32 UTC, maximoortelli commented on index.html
Thanks for your review, I have already successfully fixed all the errors in my style.css file.

2023-05-12 15:37 UTC, Shisui6 approved these changes
Hi @maximoortelli, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Nice use of media queries ✅


## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 15:42 UTC, merged